# Generated by Django 3.0.5 on 2020-04-26 19:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kheladi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('favourite_cricketer', models.CharField(max_length=30)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('country', models.CharField(max_length=7)),
                ('dob', models.DateField(default=django.utils.timezone.now, help_text='Enter in format YYYY-MM-DD')),
                ('age', models.PositiveIntegerField()),
                ('height', models.CharField(default=0, max_length=10)),
                ('role', models.CharField(choices=[('ar', 'all rounder'), ('bwl', 'bowler'), ('bts', 'batsman')], default='ar', max_length=20)),
                ('batting_style', models.CharField(choices=[('rhb', 'right hand bat'), ('lhb', 'left hand bat')], default='rhb', max_length=20)),
                ('bowling_style', models.CharField(choices=[('raf', 'right arm fast'), ('laf', 'left arm fast'), ('las', 'left arm spin'), ('ras', 'right arm spin')], default='raf', max_length=20)),
                ('highest_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('highest_wicket', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name_plural': 'Kheladi',
                'ordering': ['first_name'],
            },
        ),
    ]
