# Generated by Django 3.0.5 on 2020-04-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kheladi',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kheladi',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
