# Generated by Django 3.0.5 on 2020-04-27 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
