# Generated by Django 3.0.5 on 2020-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='kheladi',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
