# Generated by Django 3.0.5 on 2020-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
