# Generated by Django 3.0.5 on 2020-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0008_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='batting_style',
            field=models.CharField(choices=[('right hand bat', 'right hand bat'), ('left hand bat', 'left hand bat')], default='rhb', max_length=20),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='role',
            field=models.CharField(choices=[('all rounder', 'all rounder'), ('bowler', 'bowler'), ('batsman', 'batsman')], default='ar', max_length=20),
        ),
    ]
