# Generated by Django 3.0.5 on 2020-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0009_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='batting_style',
            field=models.CharField(choices=[('right hand bat', 'right hand bat'), ('left hand bat', 'left hand bat')], default='right hand bat', max_length=20),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='bowling_style',
            field=models.CharField(choices=[('right arm fast', 'right arm fast'), ('left arm fast', 'left arm fast'), ('left arm spin', 'left arm spin'), ('right arm spin', 'right arm spin')], default='right arm bowl', max_length=20),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='role',
            field=models.CharField(choices=[('all rounder', 'all rounder'), ('bowler', 'bowler'), ('batsman', 'batsman')], default='all rounder', max_length=20),
        ),
    ]
