# Generated by Django 3.0.5 on 2020-04-27 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0010_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter in format YYYY-MM-DD', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='profile picture'),
        ),
    ]
