# Generated by Django 3.0.5 on 2020-04-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0012_auto_20200427_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='dp',
            field=models.ImageField(default='profile/default_image.jpg', upload_to='profile/', verbose_name='profile picture'),
        ),
    ]
