# Generated by Django 3.0.5 on 2020-04-28 09:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0013_auto_20200427_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='age',
            field=models.PositiveIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='batting_style',
            field=models.CharField(choices=[('right hand bat', 'right hand bat'), ('left hand bat', 'left hand bat')], db_index=True, default='right hand bat', max_length=20),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='bio',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='bowling_style',
            field=models.CharField(choices=[('right arm fast', 'right arm fast'), ('left arm fast', 'left arm fast'), ('left arm spin', 'left arm spin'), ('right arm spin', 'right arm spin')], db_index=True, default='right arm bowl', max_length=20),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='country',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='dob',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Enter in format YYYY-MM-DD', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='dp',
            field=models.ImageField(db_index=True, default='profile/default_image.jpg', upload_to='profile/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='favourite_cricketer',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='height',
            field=models.CharField(db_index=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='highest_score',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='highest_wicket',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='role',
            field=models.CharField(choices=[('all rounder', 'all rounder'), ('bowler', 'bowler'), ('batsman', 'batsman')], db_index=True, default='all rounder', max_length=20),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
