# Generated by Django 3.0.5 on 2020-04-29 21:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0014_auto_20200428_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='dp',
            field=cloudinary.models.CloudinaryField(db_index=True, max_length=255, verbose_name='profile picture'),
        ),
    ]
