# Generated by Django 3.0.5 on 2020-04-29 22:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0016_cloud_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kheladi',
            name='dp',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='kheladi',
            name='favourite_cricketer',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
