# Generated by Django 3.0.5 on 2020-04-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0019_gang_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gang',
            name='in_mind',
            field=models.TextField(db_index=True, verbose_name='Whats in your mind?'),
        ),
        migrations.AlterField(
            model_name='gang',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
