# Generated by Django 3.0.5 on 2020-05-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_first_model_for_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_source',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
