# Generated by Django 3.0.5 on 2020-05-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_image_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_source',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
